In [43]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
from statsmodels.stats.outliers_influence import variance_inflation_factor
import yfinance as yf

## Functions

In [44]:
def Pagan_test(data): 
    # Create DataFrame from data dictionary
    df = pd.DataFrame(data)

    # Drop rows with missing values to avoid errors during modeling
    df = df.dropna()

    # Build the formula string dynamically from your independent variables
    independent_vars = "+".join([f"X{i}" for i in range(1, len(df.columns))])
    formula = f"Y ~ {independent_vars}"

    # Fit the OLS regression model
    model = smf.ols(formula=formula, data=df).fit()

    # Run the Breusch-Pagan test
    bp_test = sms.het_breuschpagan(model.resid, model.model.exog)
    labels = ['Lagrange multiplier statistic', 'p-value', 'f-value', 'f p-value']

    # Print Breusch-Pagan test results
    for label, value in zip(labels, bp_test):
        print(f"{label}: {value}")

def Whites_test(data):
    df = pd.DataFrame(data).dropna()

    X = df[[f'X{i}' for i in range(1, len(df.columns))]]
    X = sm.add_constant(X)
    y = df['Y']

    model = sm.OLS(y, X).fit()

    white_test = sms.het_white(model.resid, model.model.exog)

    labels = ['Test Statistic', 'Test Statistic p-value', 'F-Statistic', 'F-Test p-value']
    for label, value in zip(labels, white_test):
        print(f"{label}: {value}")

def p_valueTest(data):

    df = pd.DataFrame(data).dropna()

    # Assume df is your DataFrame with independent variables X1, X2,... and dependent variable Y
    X = df.drop('Y', axis=1)
    y = df['Y']

    # Add a constant to the model (intercept)
    X = sm.add_constant(X)

    # Fit the model
    model = sm.OLS(y, X).fit()

    # Get summary which includes p-values
    print(model.summary())

    # Or just get the p-values directly:
    p_values = model.pvalues
    print(p_values)

def LRM(data): 
    df = pd.DataFrame(data)

    df = std_filter(df)  # remove rows with missing data

    X = df.drop('Y', axis=1)
    y = df['Y']

    # Initialize and fit the model
    model = LinearRegression()
    model.fit(X, y)

    Coefs = []

    # Print coefficients to show the importance of each variable
    for var, coef in zip(X.columns, model.coef_):
        Coefs.append([var, coef])

    return Coefs

def VIF_test(data):
    df = pd.DataFrame(data).dropna()

    # Exclude dependent variable Y for VIF calculation
    X = df[[f"X{i}" for i in range(1, len(df.columns))]]

    # Add constant term for intercept
    X = sm.add_constant(X)

    # Calculate VIF for each explanatory variable
    vif_data = pd.DataFrame()
    vif_data["Variable"] = X.columns
    vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    print(vif_data)

def std_filter(data):
    means = data.mean()
    stds = data.std()    

    filtered_values = []

    for idx in range(len(data)):
        row = data.iloc[idx]

        # Check if every column's value is within mean ± std specifically for that column
        in_range = ((row >= (means - stds)) & (row <= (means + stds))).all()

        if in_range:
            filtered_values.append(row)

    df_filtered = pd.DataFrame(filtered_values, columns=data.columns)
    return df_filtered

def plot_data_log(data): 
    df = pd.DataFrame(data)

    y = df.index

    for i in data: 
        plt.plot(df[i],y, label=i, marker='o', markersize=1, linestyle='')

    plt.xscale('log')

    plt.plot(df[i],y, label="nvda", marker='o', markersize=1, linestyle='')

    plt.legend()
    plt.xlabel('Independent Variables (Log Scale)')
    plt.ylabel('NVIDIA Stock Price (Y)')
    plt.title('Stock Prices vs NVIDIA Stock Price')

def plot_data_log_y(data, dotsize=1): 
    df = pd.DataFrame(data)

    for i in data: 

        if i == "Y":
            continue

        plt.plot(df[i], df["Y"], label=i, marker='o', markersize=dotsize, linestyle='')

    plt.xscale('log')

    # plt.plot(y,df["Y"], label="nvda", marker='o', markersize=1, linestyle='')

    plt.legend()
    plt.xlabel('Independent Variables (Log Scale)')
    plt.ylabel('NVIDIA Stock Price (Y)')
    plt.title('Stock Prices vs NVIDIA Stock Price')

def plot_data_log_SAVE(data): 
    df = pd.DataFrame(data)

    y = df.index

    for i in data: 
        plt.plot(df[i], y, label=i)

    plt.xscale('log')

    plt.plot(df["Y"], y, label="nvda")

    plt.legend()

    plt.xlabel('Independent Variables (Log Scale)')
    plt.ylabel('NVIDIA Stock Price (Y)')
    plt.title('Stock Prices vs NVIDIA Stock Price')

    plt.savefig('my_high_res_plot.png', dpi=300)

def Set_index(data, index):
    for i in data: 
        i.index = index

## Stocks import

In [45]:
nvda = yf.Ticker("NVDA") #
asml = yf.Ticker("ASML") #
aapl = yf.Ticker("AAPL") #
goog = yf.Ticker("GOOG") #
tsmc = yf.Ticker("TSM") #
s_p = yf.Ticker("^GSPC")
ndx = yf.Ticker("^NDX")
spgtsi = yf.Ticker("^SPGSTI")
amd = yf.Ticker("AMD")
intel = yf.Ticker("INTL")
copper = yf.Ticker("HG=F")
gold = yf.Ticker("GC=F")
silver = yf.Ticker("SI=F")
platinum = yf.Ticker("PL=F")
uranium = yf.Ticker("URA")
coal = yf.Ticker("COAL")
qcom = yf.Ticker("QCOM")

### MODEL 1: Related Stocks

In [46]:
data1 = {
    "Y": nvda.history(start="2020-01-01")['Close'],
    "X1": asml.history(start="2020-01-01")['Close'],
    "X2": aapl.history(start="2020-01-01")['Close'],
    # "X3": goog.history(start="2020-01-01")['Close'],
    "X3": tsmc.history(start="2020-01-01")['Close'],
    "X4": intel.history(start="2020-01-01")['Close'],
    "X5": qcom.history(start="2020-01-01")['Close']
}

In [47]:
LRM1 = LRM(data1)

for i in LRM1:
    print(i)

['X1', -0.1136127183598671]
['X2', 0.5497998412624188]
['X3', 0.8442333664198658]
['X4', -2.452948262773996]
['X5', 0.18877549844724045]

In [48]:
p_valueTest(data1)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.972
Model:                            OLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     5195.
Date:                Tue, 02 Dec 2025   Prob (F-statistic):               0.00
Time:                        07:52:03   Log-Likelihood:                -2711.6
No. Observations:                 751   AIC:                             5435.
Df Residuals:                     745   BIC:                             5463.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -114.0485      8.336    -13.681      0.000    -130.414     -97.683
X1            -0.0537      0.004    -12.504      0.000      -0.062      -0.045
X2             0.1605      0.021      7.820      0.000       0.120       0.201
X3             0.5727      0.023     24.479      0.000       0.527       0.619
X4             2.5689      0.450      5.711      0.000       1.686       3.452
X5             0.5055      0.025     20.375      0.000       0.457       0.554
==============================================================================
Omnibus:                        8.523   Durbin-Watson:                   0.094
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                8.219
Skew:                          -0.221   Prob(JB):                       0.0164
Kurtosis:                       2.739   Cond. No.                     2.10e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.1e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
const    3.580514e-38
X1       1.052547e-32
X2       1.805260e-14
X3       1.462045e-97
X4       1.626030e-08
X5       1.082501e-73
dtype: float64

In [49]:
Pagan_test(data1)

Lagrange multiplier statistic: 70.58515291408567
p-value: 7.741798010484807e-14
f-value: 15.457022769626292
f p-value: 1.7534929882902347e-14

In [50]:
Whites_test(data1)

Test Statistic: 141.9103965515261
Test Statistic p-value: 2.1956782349993103e-20
F-Statistic: 8.504051694208373
F-Test p-value: 7.747405588702128e-23

In [51]:
VIF_test(data1)

  Variable         VIF
0    const  646.298697
1       X1    3.210634
2       X2    4.467578
3       X3   19.775969
4       X4   12.684868
5       X5    4.227170

### MODEL 2: yearly metal production

Importing data

In [52]:
silver_data = pd.read_excel('./Data/Silver Historical Statistics.xlsx', sheet_name="Silver")
Tin_data = pd.read_excel('./Data/Tin Historical Statistics.xlsx', sheet_name="Tin")
Silicon_data = pd.read_excel('./Data/Silicon Historical Statistics.xlsx', sheet_name="Silicon")
Aluminum_data = pd.read_excel('./Data/Aluminum Historical Statistics.xlsx', sheet_name="Aluminum")
Rare_Earths_data = pd.read_excel('./Data/Rare Earths Historical Statistics.xlsx', sheet_name="Rare earths")
Gold_data = pd.read_excel('./Data/Gold Historical Statistics.xlsx', sheet_name="Gold")

filtered_silver_data = silver_data[(124-20):124]["Unnamed: 11"]
filtered_Tin_data = Tin_data[(124-20):124]["Unnamed: 11"] 
filtered_Silicon_data = Silicon_data[(102-21):101]["Unnamed: 9"] 
filtered_Aluminum_data = Aluminum_data[(124-20):124]["Unnamed: 15"] 
filtered_Rare_Earths_data = Rare_Earths_data[(124-20):124]["Unnamed: 7"] 
filtered_Gold_data = Gold_data[(124-20):124]["Unnamed: 8"]

filtered_Silicon_data

81     3500000
82     3500000
83     3720000
84     4390000
85     4900000
86     5310000
87     5650000
88     6330000
89     6510000
90     6260000
91     6930000
92     7370000
93     7450000
94     7950000
95     7900000
96     7800000
97     7700000
98     7230000
99     8890000
100    8560000
Name: Unnamed: 9, dtype: object

In [53]:
filtered_Gold_data.index = nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last().index
filtered_silver_data.index = nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last().index
filtered_Tin_data.index = nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last().index
filtered_Silicon_data.index = nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last().index
filtered_Aluminum_data.index = nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last().index
filtered_Rare_Earths_data.index = nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last().index

In [54]:
data2 = {
    "Y": nvda.history(start="2000-01-01", end="2020-1-1")['Close'].resample('YE').last(),
    "X1": filtered_silver_data.astype(float),
    "X2": filtered_Tin_data.astype(float),
    "X3": filtered_Silicon_data.astype(float),
    "X4": filtered_Aluminum_data.astype(float),
    "X5": filtered_Rare_Earths_data.astype(float),
    "X6": filtered_Gold_data.astype(float)
}

In [55]:
for i in LRM(data2):
    print(i)

['X1', 1.3779703231570888e-07]
['X2', -1.0403920763839038e-06]
['X3', 2.4546559208183115e-07]
['X4', -2.993601739019293e-08]
['X5', 2.818489222089255e-06]
['X6', 4.1945183139069715e-09]

In [56]:
p_valueTest(data1)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.972
Model:                            OLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     5195.
Date:                Tue, 02 Dec 2025   Prob (F-statistic):               0.00
Time:                        07:52:03   Log-Likelihood:                -2711.6
No. Observations:                 751   AIC:                             5435.
Df Residuals:                     745   BIC:                             5463.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -114.0485      8.336    -13.681      0.000    -130.414     -97.683
X1            -0.0537      0.004    -12.504      0.000      -0.062      -0.045
X2             0.1605      0.021      7.820      0.000       0.120       0.201
X3             0.5727      0.023     24.479      0.000       0.527       0.619
X4             2.5689      0.450      5.711      0.000       1.686       3.452
X5             0.5055      0.025     20.375      0.000       0.457       0.554
==============================================================================
Omnibus:                        8.523   Durbin-Watson:                   0.094
Prob(Omnibus):                  0.014   Jarque-Bera (JB):                8.219
Skew:                          -0.221   Prob(JB):                       0.0164
Kurtosis:                       2.739   Cond. No.                     2.10e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.1e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
const    3.580514e-38
X1       1.052547e-32
X2       1.805260e-14
X3       1.462045e-97
X4       1.626030e-08
X5       1.082501e-73
dtype: float64

In [57]:
Pagan_test(data2)

Lagrange multiplier statistic: 6.358553802501314
p-value: 0.38424549086752013
f-value: 1.0099271274194026
f p-value: 0.4598825532062687

In [58]:
Whites_test(data2)

Test Statistic: 20.0
Test Statistic p-value: 0.39457818208600104
F-Statistic: nan
F-Test p-value: nan

In [59]:
VIF_test(data2)

  Variable         VIF
0    const  716.719690
1       X1   18.100771
2       X2    1.823068
3       X3   30.965129
4       X4   73.379265
5       X5    3.287107
6       X6   11.975217

## MODEL 3: Daily metal prices

In [60]:
data3 = {
    "X1": copper.history(start="2020-01-01")['Close'], 
    "X2": gold.history(start="2020-01-01")['Close'],
    "X3": silver.history(start="2020-01-01")['Close'],
    "X4": platinum.history(start="2020-01-01")['Close'], 
    "X5": uranium.history(start="2020-01-01")['Close'], 

    "Y": nvda.history(start="2020-01-01")['Close'], 
}

In [61]:
for i in LRM(data3):
    print(i)

['X1', -5.038588113366651]
['X2', 0.0778474162736468]
['X3', 2.054582996392905]
['X4', -0.08350004567609096]
['X5', 1.6561130343807768]

In [62]:
p_valueTest(data3)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.929
Model:                            OLS   Adj. R-squared:                  0.929
Method:                 Least Squares   F-statistic:                     3878.
Date:                Tue, 02 Dec 2025   Prob (F-statistic):               0.00
Time:                        07:52:06   Log-Likelihood:                -6076.6
No. Observations:                1483   AIC:                         1.217e+04
Df Residuals:                    1477   BIC:                         1.220e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -50.4846      3.678    -13.725      0.000     -57.700     -43.269
X1            -4.8611      0.937     -5.187      0.000      -6.699      -3.023
X2             0.0508      0.002     23.102      0.000       0.046       0.055
X3             2.3583      0.233     10.139      0.000       1.902       2.815
X4            -0.0992      0.004    -22.901      0.000      -0.108      -0.091
X5             2.5058      0.091     27.523      0.000       2.327       2.684
==============================================================================
Omnibus:                       30.333   Durbin-Watson:                   0.046
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               33.697
Skew:                           0.305   Prob(JB):                     4.82e-08
Kurtosis:                       3.415   Cond. No.                     2.41e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.41e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
const     1.947935e-40
X1        2.428222e-07
X2       4.663033e-101
X3        2.122977e-23
X4        1.424188e-99
X5       5.825506e-135
dtype: float64

In [63]:
Pagan_test(data3)

Lagrange multiplier statistic: 345.3995017890426
p-value: 1.7120606345705008e-72
f-value: 89.68966960628255
f p-value: 1.5644724607790104e-82

In [64]:
Whites_test(data3)

Test Statistic: 611.3060430218494
Test Statistic p-value: 1.1934669522359606e-116
F-Statistic: 51.26394577726467
F-Test p-value: 1.2239555914435878e-152

In [65]:
VIF_test(data3)

  Variable        VIF
0    const  94.208423
1       X1   2.879388
2       X2  11.577131
3       X3  16.340342
4       X4   3.415538
5       X5   4.853481

## MODEL 4: Monthly electricity rates

In [66]:
Excel_elec = pd.read_excel('./Data/EE-Data1.xlsx', sheet_name='Sheet1')

commercial_elec_price = Excel_elec["Unnamed: 1"][14:81].astype('float64')
industrial_elec_price = Excel_elec["Unnamed: 2"][14:81].astype('float64')

industrial_elec_price

14    6.37
15    6.44
16    6.39
17    6.39
18    6.54
      ...
75    8.23
76    8.26
77    8.21
78    8.30
79    8.86
Name: Unnamed: 2, Length: 66, dtype: float64

In [67]:
nvda.history(start="2020-01-01", end="2025-7-1")['Close'].resample('ME').last()

Date
2020-01-31 00:00:00-05:00      5.884792
2020-02-29 00:00:00-05:00      6.726119
2020-03-31 00:00:00-04:00      6.564983
2020-04-30 00:00:00-04:00      7.279261
2020-05-31 00:00:00-04:00      8.841805
                                ...
2025-02-28 00:00:00-05:00    124.892792
2025-03-31 00:00:00-04:00    108.366364
2025-04-30 00:00:00-04:00    108.906296
2025-05-31 00:00:00-04:00    135.113007
2025-06-30 00:00:00-04:00    157.981094
Freq: ME, Name: Close, Length: 66, dtype: float64

In [68]:
commercial_elec_price.index = nvda.history(start="2020-01-01", end="2025-7-1")['Close'].resample('ME').last().index
industrial_elec_price.index = nvda.history(start="2020-01-01", end="2025-7-1")['Close'].resample('ME').last().index

data4 = {
    "X1": commercial_elec_price,
    "X2": industrial_elec_price,
    "Y": nvda.history(start="2020-01-01", end="2025-7-1")['Close'].resample('ME').last()
}

In [69]:
for i in LRM(data4):
    print(i)

['X1', 46.08726764634152]
['X2', -47.05311893920663]

In [70]:
p_valueTest(data4)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.613
Model:                            OLS   Adj. R-squared:                  0.601
Method:                 Least Squares   F-statistic:                     49.94
Date:                Tue, 02 Dec 2025   Prob (F-statistic):           1.01e-13
Time:                        07:52:06   Log-Likelihood:                -312.75
No. Observations:                  66   AIC:                             631.5
Df Residuals:                      63   BIC:                             638.1
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -387.6898     44.822     -8.650      0.000    -477.259    -298.121
X1            82.2051     10.359      7.936      0.000      61.505     102.906
X2           -71.6539     13.236     -5.414      0.000     -98.104     -45.204
==============================================================================
Omnibus:                        5.574   Durbin-Watson:                   0.511
Prob(Omnibus):                  0.062   Jarque-Bera (JB):                4.693
Skew:                           0.545   Prob(JB):                       0.0957
Kurtosis:                       3.721   Cond. No.                         188.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
const    2.624793e-12
X1       4.621195e-11
X2       1.025122e-06
dtype: float64

In [71]:
Pagan_test(data4)

Lagrange multiplier statistic: 9.424588755659748
p-value: 0.008984140903610573
f-value: 5.247412953325745
f p-value: 0.007800800924524317

In [72]:
Whites_test(data4)

Test Statistic: 16.9278165893039
Test Statistic p-value: 0.004638748939551984
F-Statistic: 4.139489726217693
F-Test p-value: 0.0026931426873782584

In [73]:
VIF_test(data4)

  Variable         VIF
0    const  165.512682
1       X1    8.742090
2       X2    8.742090

## MODEL 5: News sentiment

## MODEL 6: US Congress Stock Trades

In [74]:
from congress_trades_parse import congress_trades

congress_trades

,representative,type_of_trade,amount
2025-11-12 00:00:00-05:00,Cleo Fields,Buy,"$15,001 - $50,000"
2025-11-12 00:00:00-05:00,Cleo Fields,Buy,"$100,001 - $250,000"
2025-11-10 00:00:00-05:00,Michael T. McCaul,Buy,"$100,001 - $250,000"
2025-11-03 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$15,001 - $50,000"
2025-11-18 00:00:00-05:00,Gilbert Cisneros,Buy,"$1,001 - $15,000"
...,...,...,...
2016-06-16 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$1,001 - $15,000"
2016-05-23 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$1,001 - $15,000"
2016-05-23 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$1,001 - $15,000"
2016-01-20 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$1,001 - $15,000"
2016-01-20 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$1,001 - $15,000"

In [88]:
congress_trades.head(520)

congress_trades[:520]

,representative,type_of_trade,amount
2025-11-12 00:00:00-05:00,Cleo Fields,Buy,"$15,001 - $50,000"
2025-11-12 00:00:00-05:00,Cleo Fields,Buy,"$100,001 - $250,000"
2025-11-10 00:00:00-05:00,Michael T. McCaul,Buy,"$100,001 - $250,000"
2025-11-03 00:00:00-05:00,"Whitehouse, Sheldon",Buy,"$15,001 - $50,000"
2025-11-18 00:00:00-05:00,Gilbert Cisneros,Buy,"$1,001 - $15,000"
...,...,...,...
2020-02-03 00:00:00-05:00,"Roberts, Pat",Buy,"$15,001 - $50,000"
2020-01-09 00:00:00-05:00,Ro Khanna,Buy,"$1,001 - $15,000"
2020-01-09 00:00:00-05:00,Ro Khanna,Buy,"$1,001 - $15,000"
2020-01-09 00:00:00-05:00,Ro Khanna,Buy,"$15,001 - $50,000"
2020-01-02 00:00:00-05:00,Donald Sternoff Beyer Jr,Buy,"$1,001 - $15,000"

In [ ]:
nvda.history(start="2020-01-01", end="2025-7-1")['Close']

Date
2020-01-02 00:00:00-05:00      5.971409
2020-01-03 00:00:00-05:00      5.875832
2020-01-06 00:00:00-05:00      5.900473
2020-01-07 00:00:00-05:00      5.971908
2020-01-08 00:00:00-05:00      5.983109
                                ...
2025-06-24 00:00:00-04:00    147.891647
2025-06-25 00:00:00-04:00    154.301300
2025-06-26 00:00:00-04:00    155.011261
2025-06-27 00:00:00-04:00    157.741104
2025-06-30 00:00:00-04:00    157.981094
Name: Close, Length: 1380, dtype: float64

In [77]:
date = str(nvda.history(start="2020-01-01", end="2025-7-1")['Close'].index[1])

date[:10]

'2020-01-03'

In [82]:
data6 = {
    "X1": congress_trades["amount"],
    "X2": congress_trades["representative"],
    "X3": congress_trades["type_of_trade"],
    "Y": nvda.history(start="2020-01-01", end="2025-7-1")['Close']
}

data6["Y"]

Date
2020-01-02 00:00:00-05:00      5.971409
2020-01-03 00:00:00-05:00      5.875832
2020-01-06 00:00:00-05:00      5.900473
2020-01-07 00:00:00-05:00      5.971908
2020-01-08 00:00:00-05:00      5.983109
                                ...
2025-06-24 00:00:00-04:00    147.891647
2025-06-25 00:00:00-04:00    154.301300
2025-06-26 00:00:00-04:00    155.011261
2025-06-27 00:00:00-04:00    157.741104
2025-06-30 00:00:00-04:00    157.981094
Name: Close, Length: 1380, dtype: float64

In [ ]:
df = pd.DataFrame(data6).dropna(subset=['Y'])

df

ValueError: cannot reindex on an axis with duplicate labels